"""
ContPAQ-Win AI Service - REST API Package

This package contains the FastAPI route definitions and HTTP endpoint handlers
for the AI invoice processing service.

Modules:
    routes: API route definitions including:
        - GET /health - Service health check endpoint
        - POST /extract - Single invoice PDF extraction
        - POST /extract/batch - Batch invoice extraction
        - POST /validate/rfc - RFC format validation
        - POST /validate/cfdi - CFDI compliance validation

All endpoints:
    - Return JSON responses with Pydantic model serialization
    - Include Spanish error messages for user-facing errors
    - Are documented via OpenAPI/Swagger (auto-generated by FastAPI)
    - Bind only to localhost (127.0.0.1) for security
"""

__all__ = []
